"""add user_squad table

Revision ID: 6fdf17befc20
Revises: c58bc6e354ee
Create Date: 2026-08-09 16:34:23.895727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdf17befc20'
down_revision: Union[str, Sequence[str], None] = 'c58bc6e354ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_squad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_ids', sa.String(length=500), nullable=False),
    sa.Column('free_transfers', sa.Integer(), nullable=False),
    sa.Column('bank', sa.Float(), nullable=False),
    sa.Column('last_updated_gameweek', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_squad')
    # ### end Alembic commands ###
