"""remove test field web_name_search

Revision ID: 74b43b6037e1
Revises: 8f06b26a1446
Create Date: 2026-08-06 23:25:23.724355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b43b6037e1'
down_revision: Union[str, Sequence[str], None] = '8f06b26a1446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'web_name_search')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('web_name_search', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
