"""add web_name_search field

Revision ID: 8f06b26a1446
Revises: 0206f76b2c61
Create Date: 2026-08-06 23:23:23.288018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f06b26a1446'
down_revision: Union[str, Sequence[str], None] = '0206f76b2c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historical_fixture_results', 'season',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('historical_fixture_results', 'team_h_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('historical_fixture_results', 'team_a_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('historical_fixture_results', 'team_h_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('historical_fixture_results', 'team_a_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('players', sa.Column('web_name_search', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'web_name_search')
    op.alter_column('historical_fixture_results', 'team_a_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('historical_fixture_results', 'team_h_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('historical_fixture_results', 'team_a_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('historical_fixture_results', 'team_h_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('historical_fixture_results', 'season',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
