"""baseline schema

Revision ID: c58bc6e354ee
Revises: 
Create Date: 2026-08-09 09:10:54.556874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c58bc6e354ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameweeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('deadline_time', sa.DateTime(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=5), nullable=False),
    sa.Column('strength_overall_home', sa.Integer(), nullable=False),
    sa.Column('strength_overall_away', sa.Integer(), nullable=False),
    sa.Column('strength_attack_home', sa.Integer(), nullable=False),
    sa.Column('strength_attack_away', sa.Integer(), nullable=False),
    sa.Column('strength_defence_home', sa.Integer(), nullable=False),
    sa.Column('strength_defence_away', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=True),
    sa.Column('team_h_id', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_h_difficulty', sa.Integer(), nullable=False),
    sa.Column('team_a_difficulty', sa.Integer(), nullable=False),
    sa.Column('kickoff_time', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('team_h_score', sa.Integer(), nullable=True),
    sa.Column('team_a_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_h_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_fixture_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=True),
    sa.Column('team_h_id', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_h_score', sa.Integer(), nullable=False),
    sa.Column('team_a_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_h_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('second_name', sa.String(length=50), nullable=False),
    sa.Column('web_name', sa.String(length=50), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=3), nullable=False),
    sa.Column('now_cost', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('chance_of_playing_next_round', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_gameweek_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('goals_scored', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('clean_sheets', sa.Integer(), nullable=False),
    sa.Column('expected_goals', sa.Float(), nullable=False),
    sa.Column('expected_assists', sa.Float(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('clearances_blocks_interceptions', sa.Integer(), nullable=False),
    sa.Column('tackles', sa.Integer(), nullable=False),
    sa.Column('recoveries', sa.Integer(), nullable=False),
    sa.Column('defensive_contribution', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'gameweek_id', name='uq_player_season_gw')
    )
    op.create_table('player_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('predicted_points', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'gameweek_id', name='uq_prediction_player_season_gw')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_predictions')
    op.drop_table('player_gameweek_stats')
    op.drop_table('players')
    op.drop_table('historical_fixture_results')
    op.drop_table('fixtures')
    op.drop_table('teams')
    op.drop_table('gameweeks')
    # ### end Alembic commands ###
